"""Embedded Ed25519 public verify-key (auto-generated).

Generated by ``tools/init_keys.py`` — DO NOT edit by hand. Re-running
the generator will rotate this file and *revoke every license key
ever issued* against the previous keypair.

This file is checked into the customer build deliberately: knowing
the public key does not let an attacker forge license keys, only
verify them. The matching private key lives at ``.private_key`` on
the admin's machine and never ships.
"""

# Hex-encoded raw Ed25519 public key (32 bytes).
PUBLIC_KEY_HEX = "bd62f5a8914cc5c4378f7bdc43f9dd349cfb1a7468f60685410fbc5e73fbaf2c"
