"""On-PC RTMP server for v1.8.0's "Mode B" — no-USB live path.

Why this module exists
----------------------

NP Create's classic flow ("Mode A") requires:

  PC → USB cable → ADB → patched-TikTok APK → install → live

Customers on Windows that lack the right OEM USB driver (Xiaomi/
Redmi/POCO are particularly bad — see v1.7.11's driver-help
dialog) get stuck before the wizard ever sees the device.

"Mode B" eliminates the USB layer entirely. The architecture is::

    [PC]
      ffmpeg loops video.mp4
        ↓ pipe (h264/aac)
      mediamtx (RTMP server, port 1935)
        ↑ rtmp://<PC-IP>:1935/live
        |
        | WiFi (same LAN)
        ↓
    [Phone]
      Virtual-Camera app (CameraFi / Larix / DU Recorder)
        — pulls RTMP, exposes a virtual camera
        ↓
      TikTok (unmodified, from Play Store)
        — sees the virtual camera, streams normally

What this module does
---------------------

* Wraps the bundled MediaMTX binary
  (``platform_tools.find_mediamtx``) as a subprocess.
* Generates a minimal ``mediamtx.yml`` on every start with only
  the RTMP listener enabled — RTSP, HLS, WebRTC, SRT, and the
  control API are all turned off so a customer's anti-virus
  doesn't get spooked by 5 listening ports for "free".
* Picks the LAN IP the phone should connect to and exposes it
  as ``rtmp_url_for_phone`` (so the wizard can render a QR
  code). 127.0.0.1 / loopback is detected and reported back
  so the UI can warn the customer that their PC isn't on a
  routable network yet.
* Cleanly stops the child on exit and on duplicate ``start()``
  calls (we kill any prior mediamtx on the configured port via
  taskkill / pkill so customers who close-and-reopen the wizard
  don't see "address already in use").

Inspired by — but does not copy code from — UltimateRerun4.9's
``rtmp_server.py``. The yml schema and CLI args are MediaMTX's
own public interface.
"""

from __future__ import annotations

import logging
import os
import platform
import socket
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Callable, Optional

from . import platform_tools

log = logging.getLogger(__name__)

# Hide the cmd flicker on Windows when we spawn mediamtx. Same
# trick UltimateRerun uses; without it customers see a black
# console window pop briefly every time the server starts, which
# looks broken even though it's not.
_NO_WINDOW = (
    subprocess.CREATE_NO_WINDOW  # type: ignore[attr-defined]
    if sys.platform == "win32"
    else 0
)


_DEFAULT_RTMP_PORT = 1935


def get_local_ip() -> str:
    """Return the LAN IP this PC will advertise to the phone.

    We open a UDP socket "to" 8.8.8.8 (no packet actually
    leaves; UDP just resolves the routing table for us) and
    read the local end of the socket. This is the one
    technique that consistently picks the right interface
    when a machine has multiple (Wi-Fi + Ethernet + VPN) —
    socket.gethostbyname(hostname) often returns 127.0.1.1
    on Linux and the wrong NIC's IP on Windows.

    Returns "127.0.0.1" when there's no usable route, which
    is the unambiguous "you're offline / not on a LAN" signal
    the UI can act on.
    """
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            s.connect(("8.8.8.8", 80))
            return s.getsockname()[0]
        finally:
            s.close()
    except Exception:
        return "127.0.0.1"


def _generate_config(port: int) -> str:
    """Build the smallest mediamtx.yml that does what we need.

    We turn EVERYTHING but RTMP off:

    * ``rtsp/hls/webrtc/srt: no`` so we only bind one port
    * ``api/metrics/pprof/playback: no`` so no HTTP control
      surface — our supervisor talks to mediamtx via SIGTERM
      only, which is portable and doesn't risk customers
      stumbling onto an open admin endpoint.
    * ``logLevel: warn`` keeps the captured stdout small —
      the wizard tails it and shows the last few lines on
      error.
    * ``paths: all_others / source: publisher`` accepts any
      stream name (live, live2, foobar) so power users can
      multi-stream without us hardcoding a path list.
    """
    return (
        f"# NP Create -- generated by rtmp_server.py at startup\n"
        f"# DO NOT edit by hand; this file is overwritten on every start.\n"
        f"logLevel: warn\n"
        f"logDestinations: [stdout]\n"
        f"\n"
        f"# Single-protocol mode — RTMP only.\n"
        f"rtsp: no\n"
        f"hls: no\n"
        f"webrtc: no\n"
        f"srt: no\n"
        f"\n"
        f"rtmp: yes\n"
        f"rtmpAddress: :{port}\n"
        f"rtmpEncryption: \"no\"\n"
        f"\n"
        f"# Disable optional services (no admin/metrics surface).\n"
        f"api: no\n"
        f"metrics: no\n"
        f"pprof: no\n"
        f"playback: no\n"
        f"\n"
        f"pathDefaults:\n"
        f"  source: publisher\n"
        f"  record: no\n"
        f"\n"
        f"paths:\n"
        f"  all_others:\n"
        f"    source: publisher\n"
    )


def _kill_stale_mediamtx() -> None:
    """Best-effort kill of any orphaned mediamtx from a prior
    run that didn't shut down cleanly (e.g. customer closed
    the app via Task Manager). Failures are logged and
    ignored — if there's nothing to kill, the start() call
    will succeed regardless.
    """
    name = "mediamtx.exe" if sys.platform == "win32" else "mediamtx"
    try:
        if sys.platform == "win32":
            subprocess.run(
                ["taskkill", "/F", "/IM", name],
                capture_output=True, timeout=5,
                creationflags=_NO_WINDOW,
            )
        else:
            subprocess.run(
                ["pkill", "-f", name],
                capture_output=True, timeout=5,
            )
    except Exception:
        log.debug("kill stale mediamtx: ignoring failure", exc_info=True)


class RTMPServer:
    """Supervises the bundled MediaMTX binary as a child process."""

    def __init__(
        self,
        port: int = _DEFAULT_RTMP_PORT,
        log_callback: Optional[Callable[[str], None]] = None,
    ) -> None:
        self.port = port
        self._log_cb = log_callback
        self._proc: Optional[subprocess.Popen] = None
        self._running = False
        self._local_ip = "127.0.0.1"
        self._stdout_thread: Optional[threading.Thread] = None
        self._last_stderr_lines: list[str] = []

    # ── small helpers ────────────────────────────────────────

    def _emit(self, msg: str) -> None:
        log.info(msg)
        if self._log_cb:
            try:
                self._log_cb(msg)
            except Exception:
                log.debug("rtmp log_callback raised", exc_info=True)

    @property
    def is_running(self) -> bool:
        return self._running and self._proc is not None and self._proc.poll() is None

    @property
    def rtmp_url(self) -> str:
        """URL the *PC's own* FFmpeg publishes to (loopback)."""
        return f"rtmp://127.0.0.1:{self.port}/live"

    @property
    def rtmp_url_for_phone(self) -> str:
        """URL the *phone* connects to (LAN IP)."""
        return f"rtmp://{self._local_ip}:{self.port}/live"

    @property
    def is_lan_routable(self) -> bool:
        """False = we're on loopback only; the phone can't
        reach this PC. UI uses this to show "join a Wi-Fi
        network first" instead of a useless QR code."""
        return self._local_ip not in ("127.0.0.1", "0.0.0.0")

    def get_local_ip(self) -> str:
        return self._local_ip

    # ── lifecycle ────────────────────────────────────────────

    def start(self) -> bool:
        """Spawn mediamtx with our generated config. Returns
        True if the server is alive after a brief settle
        period; False (and emits a log line with the captured
        stderr tail) otherwise.
        """
        if self.is_running:
            return True

        bin_path = platform_tools.find_mediamtx()
        if bin_path is None:
            self._emit(
                "❌ ไม่พบ mediamtx — ตัว binary ยังไม่ได้ bundle "
                "กับโปรแกรมนี้ (รัน tools/setup_ci_tools.py "
                "หรือติดต่อแอดมิน)"
            )
            return False

        # Wipe any stragglers from a crash so bind doesn't fail.
        _kill_stale_mediamtx()

        cfg_path = bin_path.parent / "mediamtx.yml"
        try:
            cfg_path.write_text(_generate_config(self.port), encoding="utf-8")
        except OSError as e:
            self._emit(f"❌ เขียน mediamtx.yml ไม่ได้: {e}")
            return False

        try:
            self._proc = subprocess.Popen(
                [str(bin_path), str(cfg_path)],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
                cwd=str(bin_path.parent),
                text=True,
                encoding="utf-8",
                errors="replace",
                creationflags=_NO_WINDOW,
            )
        except OSError as e:
            self._emit(f"❌ เปิด mediamtx ล้มเหลว: {e}")
            return False

        # mediamtx prints "ready" on startup or exits within
        # ~200ms on bad config / port-in-use. Give it 1.5s to
        # decide before declaring success.
        time.sleep(1.5)
        if self._proc.poll() is not None:
            tail = ""
            try:
                tail = (self._proc.stdout.read(800) or "").strip() if self._proc.stdout else ""
            except Exception:
                pass
            self._emit(
                f"❌ mediamtx ออกทันทีหลัง start "
                f"(exit={self._proc.returncode})\n{tail}"
            )
            self._proc = None
            return False

        self._running = True
        self._local_ip = get_local_ip()
        self._stdout_thread = threading.Thread(
            target=self._read_stdout, daemon=True
        )
        self._stdout_thread.start()

        self._emit(f"✅ RTMP server เริ่มแล้ว ({self.rtmp_url_for_phone})")
        return True

    def stop(self) -> None:
        if self._proc is not None:
            try:
                self._proc.terminate()
                try:
                    self._proc.wait(timeout=3)
                except subprocess.TimeoutExpired:
                    self._proc.kill()
            except Exception:
                log.debug("rtmp stop: ignoring failure", exc_info=True)
            self._proc = None
        self._running = False
        self._emit("RTMP server หยุดแล้ว")

    # ── stdout pump ──────────────────────────────────────────

    def _read_stdout(self) -> None:
        """Drain mediamtx's stdout/stderr so the pipe doesn't
        backfill and block the child. We keep the last 50
        WRN/ERR lines for ``last_errors()`` so the UI's
        diagnostic page can show recent failures without
        opening a log file."""
        proc = self._proc
        if proc is None or proc.stdout is None:
            return
        try:
            for line in proc.stdout:
                line = line.rstrip()
                if not line:
                    continue
                if "ERR" in line or "WRN" in line:
                    self._last_stderr_lines.append(line)
                    if len(self._last_stderr_lines) > 50:
                        self._last_stderr_lines.pop(0)
                    log.debug("[mediamtx] %s", line)
        except Exception:
            log.debug("rtmp stdout pump: died", exc_info=True)

    def last_errors(self) -> list[str]:
        return list(self._last_stderr_lines)

    # ── port probe (for UI) ──────────────────────────────────

    def is_port_in_use(self) -> bool:
        """Quick check used by the UI before showing 'start':
        if some other RTMP server (OBS, nginx-rtmp) is already
        bound, we want to surface that as a friendly error
        instead of a generic "mediamtx exited" message."""
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.settimeout(1.0)
            try:
                rc = s.connect_ex(("127.0.0.1", self.port))
                return rc == 0
            finally:
                s.close()
        except Exception:
            return False
