#!/usr/bin/env python3
"""Live Studio Pro — admin keypair initialiser (run ONCE).

Generates an Ed25519 keypair used for signing license keys::

    vcam-pc/.private_key      ← 32-byte hex seed (admin only, gitignored)
    vcam-pc/src/_pubkey.py    ← public verify-key, baked into source

The public key is baked into the source tree so the customer build
is self-contained: when we ZIP up the customer bundle we ship the
already-existing ``_pubkey.py`` and *strip* the ``.private_key`` file
(see ``tools/build_release.py``).

Threat model
~~~~~~~~~~~~

The customer can read every byte of their bundle. With Ed25519 that
is fine — the bundle ships only the *public* key, which can verify
signatures but cannot create new ones. The private key never leaves
the admin's machine.

Usage::

    python tools/init_keys.py            # refuse if files already exist
    python tools/init_keys.py --force    # overwrite (revokes all old keys!)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
sys.path.insert(0, str(PROJECT))

from src import _ed25519 as ed  # noqa: E402

PRIVATE_KEY_PATH = PROJECT / ".private_key"
PUBKEY_MODULE = PROJECT / "src" / "_pubkey.py"


PUBKEY_TEMPLATE = '''"""Embedded Ed25519 public verify-key (auto-generated).

Generated by ``tools/init_keys.py`` — DO NOT edit by hand. Re-running
the generator will rotate this file and *revoke every license key
ever issued* against the previous keypair.

This file is checked into the customer build deliberately: knowing
the public key does not let an attacker forge license keys, only
verify them. The matching private key lives at ``.private_key`` on
the admin's machine and never ships.
"""

# Hex-encoded raw Ed25519 public key (32 bytes).
PUBLIC_KEY_HEX = "{pub_hex}"
'''


def write_pubkey_module(pub: bytes) -> None:
    PUBKEY_MODULE.write_text(
        PUBKEY_TEMPLATE.format(pub_hex=pub.hex()),
        encoding="utf-8",
    )


def write_private_key(seed: bytes) -> None:
    PRIVATE_KEY_PATH.write_text(seed.hex() + "\n", encoding="utf-8")
    try:
        PRIVATE_KEY_PATH.chmod(0o600)
    except OSError:
        # Windows can't always honor 0600; the gitignore + bundle
        # filter is our real protection there.
        pass


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Initialise license keypair")
    p.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing key files (revokes all old keys)",
    )
    args = p.parse_args(argv if argv is not None else sys.argv[1:])

    has_priv = PRIVATE_KEY_PATH.is_file()
    has_pub = PUBKEY_MODULE.is_file()
    if (has_priv or has_pub) and not args.force:
        print(
            "[!] Keypair already exists:\n"
            f"      private: {PRIVATE_KEY_PATH}\n"
            f"      public : {PUBKEY_MODULE}\n"
            "    Pass --force to rotate (this will REVOKE every license\n"
            "    key you've already issued).",
            file=sys.stderr,
        )
        return 2

    seed = ed.random_seed()
    priv, pub = ed.keypair_from_seed(seed)
    write_private_key(priv)
    write_pubkey_module(pub)

    print()
    print("  ╭─── Live Studio Pro — keypair initialised ────────────")
    print(f"  │ Private : {PRIVATE_KEY_PATH.relative_to(PROJECT)}")
    print(f"  │           (HEX) {priv.hex()[:16]}…")
    print(f"  │ Public  : {PUBKEY_MODULE.relative_to(PROJECT)}")
    print(f"  │           (HEX) {pub.hex()[:16]}…")
    print( "  ╰──────────────────────────────────────────────────────")
    print()
    print("  • Back up .private_key to your password manager NOW.")
    print("  • Losing it means you cannot issue any more license keys")
    print("    that match the customer builds you've shipped.")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
